version: '3.8'

services:
  ubuntu-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/src/app
    environment:
      - ENV_VAR_NAME=value
    networks:
      - ubuntu-network

networks:
  ubuntu-network:
    driver: bridge